[versions]

[libraries]

[plugins]
champeau-jmh = "me.champeau.jmh:0.7.3"
# @pin - version is self-hosted
license = "com.github.hierynomus.license:0.16.2-37dde1f"
scalastyle = "com.github.alisiikh.scalastyle:3.5.0"
shadowjar = "com.github.johnrengelman.shadow:7.1.2"
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:1.0.1"
